name: "Deployment Action"
description: "Creates a GitHub Deployment"
author: "chrnorm"
branding:
  icon: arrow-up
  color: black
inputs:
  initial_status:
    description: "Initial status for the deployment"
    default: "pending"
  run_id:
    description: "Id of the workflow run"
  token:
    description: "Github repository token"
  target_url:
    description: "Target url location"
  ref:
    description: "The ref to deploy. This can be a branch, tag, or SHA"
  description:
    description: "Descriptive message about the deployment"
  environment:
    description: "The name of the environment for the deployment"
    default: "production"
  transient_environment:
    description: "Specifies if the given environment is specific to the deployment and will no longer exist at some point in the future"
    default: "false"
outputs:
  deployment_id:
    description: "The ID of the created deployment"
runs:
  using: "node12"
  main: "dist/index.js"
